### PR TITLE
jsdoc

### PR DESCRIPTION
**Pull request by brettz9**
- npm: Add `eslint` to test script
- npm: Add scripts/server for building and opening JSDoc
- npm: Add to ignore file

### CODE REVIEW

**Comment by brettz9** [comment]
I figured I'd push this one out before tackling the Rollup... If this is ok... I wouldn't worry about the functions jsdoc ends up documenting as "global" as I can document them as belonging to the given module rather than being globals, but this will be easier to do at the same time as Rollup.

**Comment by thelonious** [comment]
Sweet! FWIW, I'm also porting these changes over to the kld-affine and kld-polynomial modules, modules on which this module depends.

**Comment by brettz9** [comment]
FYI, in PR #37 , because the packages are not bundled together, I used the jsdoc `@external` tag to refer to kld-affine and kld-polynomial objects. We could add a `@see` which JSDoc would turn into a link if you have a URL we can point to for hosting the affine and polynomial docs (another advantage for keeping the `dist` files in the repo--you might use Github pages for the hosting).

**Comment by thelonious** [comment]
I was hoping to host the docs as github pages

**Pull request merged**
