### PR TITLE
Linting - eslint-config-ash-nazg

### PR DESCRIPTION
**Pull request by brettz9**
- Linting: Apply stricter eslint-config-ash-nazg rules, disabling some frequently differing stylistic rules and temporarily disabling some import-related rules (until may submit ESM PR); disable valid-jsdoc due to current expectation of a period in description (and as valid-jsdoc is deprecated in its current form anyways); also disabled Intersection.js rules camelcase, eqeqeq, and no-labels
- npm: Add ignore file (including examples and tests); also addressses linting rule related to complaints about required file not being part of deps (if not including in npm distribution, then not an issue)

Hi,

I see you've since added some linting changes of your own. While I can rebase on them, and adjust accordingly, I thought you might take a look here first and see what you thought. In your recent changes, while you applied two of the plugins I had in place, this PR applies the entire config (including those two plugins).

I tried to keep stylistic rules you had in place, but if there had been some significant inconsistency, I favored enforcing my own rules (e.g., spaces by parentheses or single quotes over double). But I should be able to adjust these as you like.

I intend to answer your question in #33 about `overrides` over there.

### CODE REVIEW

**Comment by brettz9** [comment]
I've just now added an additional commit re: Markdown linting...

**Comment by thelonious** [comment]
Darn. And I thought I was being proactive. I'll give your `.eslintrc.js` file a try to see how it effects things. I'm having trouble with merges

**Comment by brettz9** [comment]
I guess it may be easier to apply your changes on top of mine as there will be many changes required...

**Comment by brettz9** [comment]
Re: merges, I'm a big fan of Sourcetree if you are open to GUIs...

**Comment by thelonious** [comment]
I ended up grabbing your `eslintrc.js` file and tried it out on a new branch. It took a while to get all of the required node modules (didn't install automatically for some reason, so I'm sure I was doing something wrong). Phew...1500+ problems.

- I'd like to stay with double-quotes. I have my reasons and their purely subjective
- I agree with removing extra spaces. That was just a thing I did back in 2004
- This would be a good time to drop `var` for `let` and `const`. I think that would remove all the "move vars to top of scope" errors as well
- I'm definitely in agreement with `===` vs `==`. I did not understand the nuance back in 2004
- I know this is non-standard, but I prefer `else {` on their own lines for multiple subjective reasons. That's a hang over influence from Perl.
- Hmm, use object destructuring for `var length = points.length`?
- for-of would be nice to use
- Regarding JSDoc errors, I can't get to their site. Is this still the preferred way to document JS?
- I'm on the fence regarding camelcase...doesn't seem worth changing right now

How would you suggest fixing imports?

**Comment by thelonious** [comment]
FWIW, here's the list of errors/warnings I am seeing (37 in total):

- @mysticatea/block-scoped-var
- block-scoped-var
- brace-style
- camelcase
- comma-dangle
- comma-spacing
- eqeqeq
- eslint-comments/no-unused-disable
- import/newline-after-import
- import/order
- jsdoc/check-param-names
- jsdoc/check-tag-names
- jsdoc/check-types
- jsdoc/require-param
- jsdoc/require-returns
- jsdoc/valid-types
- no-array-constructor
- no-eq-null
- no-labels
- no-lonely-if
- no-mixed-requires
- no-sequences
- no-shadow
- no-unused-expressions
- no-var
- node/no-deprecated-api
- node/no-unpublished-require
- node/shebang
- object-curly-spacing
- padded-blocks
- prefer-const
- prefer-destructuring
- require-jsdoc
- semi-spacing
- space-in-parens
- unicorn/no-for-loop
- vars-on-top

I'll have to look at samples of each. Is there a way to `--fix` only certain errors? Or does one simply edit the `.eslintrc.js` to reduce it to the set of interest?

**Comment by thelonious** [comment]
nm on my `--fix` question...I just RTFM :)

**Comment by brettz9** [comment]
Regarding double-quotes, and `else` brace style, I've applied your preferences. It should be a lot easier to see the diffs in this PR now.

Regarding `===` vs `==`, I made an exception for the `Intersection.js` file as I am not as familiar with the code to be able to correctly apply it (e.g., these operators [deal differently](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness) with `NaN` and `+0` vs. `-0`, so I think I'd need to ask you to change them if you wanted to change them). Similarly, I didn't bother with changing camel case in that particular file, nor did I change your use of labels (e.g., to break/continue).

As far as object destructuring for `var length = points.length`, the reason I did `const {length: len} = points` is because the `no-shadow` rule is on, and `window.length` is a [global](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness) which `length` would be shadowing. I also renamed `test` inside of a file for this reason (since I followed your change to move `env: "mocha"` to the whole project rather than overriding the test files only, and this environment defines `test` as a global).

Regarding JSDoc, it is still the preferred way, though the project does not seem to be maintained on a very aggressive schedule. However, Typescript has become very popular, but because it subsumes much of JSDoc anyways, unless you determine to start using their non-standard syntax, you will be compatible with Typescript anyways, with a few exceptions: https://github.com/Microsoft/TypeScript/wiki/JSDoc-support-in-JavaScript .

Regarding the annoying lack of rule-specific `--fix`, I'd just temporarily change the config file to be a single rule. :)

I'd recommend taking a look at the diffs here on Github as the changes are now not so many. I'm happy to rebase to incorporate your preferences as I can.

**Comment by brettz9** [comment]
As far as imports--and this is the reason I didn't indicate "commonjs" on this PR or remove the `"sourceType": "module"` from `parserOptions`--my intention for the next proposed PR would be to convert source to ES modules and use Rollup to convert this to UMD (so as to continue working in Node or older browsers) and to provide a bundled ESM distribution (so modern browsers, e.g., for demos, could have the convenience of being able to use ESM modules directly with your library, avoiding polluting their HTML with extra script tags or having the unexplained "magic" (in the context of their JavaScript files) of not knowing from where certain globals are coming).

**Comment by brettz9** [comment]
Rollup is by far the easiest and most well-documented solution. Webpack has some added features, but it is not as friendly to use, and it also doesn't yet support providing an ESM distribution. Besides, Rollup has been recommended for libraries and Webpack for applications.

**Comment by brettz9** [comment]
Rollup also has plugins which can handle things like commonjs imports, and Babel (so we could add even more ES6 in source while working in older browsers--e.g., ES6 classes).

**Comment by thelonious** [comment]
These changes look great. If you're able to resolve the merge conflicts, I'd be happy to merge these in. If not, I can take a pass on that.

I do have to say that the `var length = points.length` changes to destructured assignment looks odd to me, but maybe that will motivate me to use better variables names in their place. Also, there was at least one spot where the code could switch to for-of to drop the need for that temporary variable.

Thanks for the clarification on JSDoc.

I'll have to read up on UMD, ESM, etc.

**Comment by brettz9** [comment]
I've caught the case where for-of can be used and in merging I also did the following:

1. Add missing "use strict" directives
2. Remove rules redundant with config
3. Apply `no-multi-spaces` and enforce current style of `arrow-parens` being only as needed
4. Make `space-infix-ops` apply only to Intersection file
5. Remove temporary variables made redundant with destructuring

As far as a replacement for `var length = points.length`, we can turn the global of "length" off, and just allow that one if you prefer (or rename but do not restructure, e.g., `const len = points.length;`). Or, though I'm not sure of what effect this may have on performance, one could refactor to avoid lengths and just use array extras like `forEach` (including `i` within its callback). Lastly, one could use Array `entries` with the pattern, `for (const [i, a1] of points.entries())`, though one might need the proposed Babel PR for the latter.

**Comment by brettz9** [comment]
Btw, I could submit a PR for the Rollup if you like, but it'd be nice to know if you were ok forgoing the current `module.exports` style of some files in favor of `export` as I believe bundlers if not JS engines can intelligently ignore the unimported code.

**Comment by thelonious** [comment]
@brettz9, thanks so much for all of this work. It feels really good to see this code (and module) getting modernized.

This all looks great. If a Rollup PR isn't too involved for you, that sounds great. I need to see what all is involved with that, particularly with whatever code generation/processing that needs to be done. Of course, it's important to focus on the consumers of this module, but it needs to be easy for the maintainers to use as well.

**Comment by brettz9** [comment]
Very glad to hear, and I very much appreciate both the impressive work in your library and your responsiveness in these PRs... After Rollup, I should have one more item of interest, to see about hooks that may be needed so that the svg-intersections fork of your project can provide its API on top of yours.

**Comment by brettz9** [comment]
Oh, and I think you'll find Rollup rather intuitive...

**Comment by thelonious** [comment]
I'll be curious to see what hooks you have in mind. The current API is very simple (on purpose). If one needs a convenience layer, it's pretty easy to build a variation of [Shapes](https://github.com/thelonious/kld-intersections/blob/development/lib/Shapes.js) and [AffineShapes](https://github.com/thelonious/kld-intersections/blob/development/lib/AffineShapes.js).These act as adapters between the user's custom data structures and what this lib consumes. Unfortunately, you do have to use my [Point2D](https://github.com/thelonious/kld-affine/blob/development/lib/Point2D.js) type, but, again, the adapter can generate those on the fly as needed instead of requiring the user's lib to pollute their code with my classes.

**Comment by brettz9** [comment]
Regarding hooks, it is possible that the hooks are now all present in your code anyways. The API of the fork is shown at https://github.com/signavio/svg-intersections#usage-example which adds more SVG-like constructs. I'd personally like to take this a step further and accept actual SVG elements as well.

**Comment by thelonious** [comment]
Yeah, it should be pretty similar now. Have a look at:

- [Shapes API](https://github.com/thelonious/kld-intersections#shapes-api)
- [AffineShapes API](https://github.com/thelonious/kld-intersections#affine-shapes-api)

The main difference between those is that the AffineShapes version uses my Point2D classes (and later, probably Matrix2D as well). There's also a brief discussion on making your own:

- [Use Your Own Objects](https://github.com/thelonious/kld-intersections#use-your-own-objects)

Now that I look at that doc, I need to show some JSON-like snippets to make it more obvious what is going on.

Regarding accepting actual SVG elements, that was my desire as well, but I wanted that to be in another module that uses this one so this one can be used outside of SVG.

**Comment by brettz9** [comment]
As far as accepting actual SVG elements, do you have plans for releasing your own library for this? I don't know if the author of svg-intersections may be interested in this.

Not sure what you think of it, or whether you'd just prefer this as part of an external API, but I think it has become more common in JavaScript for people to use a single object as argument (and often for return value as well), being helpful for:

1. Ensure calling code is more readable and with a lesser burden on memory of argument order (e.g., `Shapes.circle({cx: 50, cy: 100, r: 300})`), also possibly allowing for aliases (e.g., accepting `radius` or `r`).
2. Where arguments are optional, allows for only those arguments actually used to be passed in (no need for passing `null` to skip over an argument, for example).
3. When passing back objects, object destructuring allows for getting out only the properties desired (more cleanly and with less burden on the memory than array destructuring, e.g., `const {radius} = circleProperties;` rather than `const [, , radius] = circleProperties`).

Also, one other small suggestion--would you consider exposing `Intersection.intersect` as just `intersect` as well for a nice succinct import, given how this method seems to justify itself for its own shorthand compared to the more particular intersection methods? Not a big deal, just a thought...

**Comment by brettz9** [comment]
Also, if I could be lazy and just ask without checking--can the arguments in the API be supplied as strings or must I first convert to numbers?

**Comment by thelonious** [comment]
To answer your question about SVG element support, have a look at [SvgShapes](#https://github.com/thelonious/kld-intersections/blob/development/lib/SvgShapes.js). I just starting writing this about an hour ago. It has not been fully tested, but have a look at [circle-circle-intersection](#https://github.com/thelonious/kld-intersections/blob/development/scratchpad/svg-circle-test.svg) and [path-line-intersection](#https://github.com/thelonious/kld-intersections/blob/development/scratchpad/svg-path-test.svg) to get a sense of how it might work. Basically, you send a single method an SVG element and it converts it to IntersectionArgs. The rest is the same after that.

Regarding changing the API, this is why I built the library as it is. Think of each of the *Shapes and syntactic interfaces (syntactic sugar). You are more than welcome to create your own Shapes-like class with whatever API you want. I'm not willing to change the Shapes class, but I'd gladly accept a new Shapes-like class using what you propose. Does that sound reasonable?

Regarding exposing `intersect` by itself, I would be fine with that, but why stop there? Shouldn't one be able to pick and choose whatever intersection method they want to use? Or is that overkill?

The API expects everything to be numbers accept for the two flags in arc segments. Those are expected to be booleans.

Just to clarify a few intentional architecture notes, I think a reasonable goal of this library is to be fast. Indeed the work @Quazistax has done is pretty impressive. I'm slowly incorporating that into the code-base. I mention this because some of the methods are called numerous times during the calculation of an intersection. If we can avoid runtime type checking and validation, we get more speed. I realize this is not as friendly as it could be, but, again, this is a convenience/performance trade off. Admittedly, I've waffled on this point in the code, but I hope to have a single philosophy throughout, at some point.

**Comment by thelonious** [comment]
Oops...fixed links in last post

**Comment by brettz9** [comment]
SvgShapes looks like exactly what I need. And I understand about the API and performance. I plan to take a closer look at the code, though if you've got a lot of work left, I can wait a bit.

As far as exposing `intersect`, I guess it's not such a big deal if there are libraries like `SvgShapes` which handle this. If you wanted to expose the other intersection methods, it'd probably make more sense as an entirely different repo, but since `Shapes` and `Intersection` are closely related in this context, I'd guess that could be overdoing it. I'm big on those clean APIs though as for every minor distraction, I otherwise get lost in my own code! :)

**Comment by thelonious** [comment]
If you look at SvgShapes, I think you'll be surprised how little code there actually is. The biggest missing piece in there is the conversion of rounded rectangles to paths. I have that code (in multiple places) already. I just need to bring it in there.

I converted all of the test SVGs I had on my site to unit tests. I'm planning on converting these into standalone SVGs like the two I pointed to above. Those will serve as a sanity check for SvgShapes. I really don't expect much to change. I have, however, found one bug in PathHandler, the class that converts path data to shapes. So, tests are starting to do their job.

I too don't like invoking `Intersection.intersect()`. It almost feels like Java. Maybe we leave `Intersection` exposed like it is now, but add another export so you can grab just `intersect`? I would certainly love hearing "clean" associated with any API I've built :)

**Comment by brettz9** [comment]
That's cool about the SVG unit tests. Were those the "visual tests" I saw? 

Speaking of tests, if you ever need UI tests to see behavior in the browser (though more for an application), I highly recommend [testcafe](https://devexpress.github.io/testcafe/documentation/getting-started/). (Not specific need perceived, just mentioning.)

Btw, if your exports, such as `SvgShapes` are of the named rather than default variety, e.g., `export {circle, rectangle}` (or `export const circle = ` or `export function circle () {`), besides allowing for more choice/convenience to users in importing, bundlers can also ignore the unused exports, minimizing the code. And you can even use this syntax while keeping the same `index.js` API if you wish by reexporting, e.g.:

**index.js**
```
import * as SvgShapes from './SvgShapes.js';
export {SvgShapes};
```

In this way, a consuming library (at least one doing its own bundling), could import the `SvgShapes.js` file directly with the methods it needed.

But if you actually wanted to expose them all, it would be:

```js
export * from  './SvgShapes.js';
```

**Comment by thelonious** [comment]
I think I have a 'visual-test' folder in kld-affine, but I have similar stuff in kld-contours and now kld-intersections. Yeah, they're basically a way to visually verify that something is working as expected. I've used this in some of my SVG implementations, but you don't get reliable pixel-for-pixel rendering per platform (probably not even per browser, I would expect). Still, I think in pictures, so its help to me.

I'll checkout testcafe. Thanks!

I know you were just giving me an example, but unfortunately, SvgShapes dispatches to other methods based on an element's tagName. Bundlers wouldn't be able to throughout unused code in that class, since it couldn't know what it unused. But, back to your points, I think for me, I'll just have to start using this import style more to get a better idea of what feels right. I'm a little cautious to do that now only because I'm not super familiar with it. I am still OK exposing `intersect` by itself though :)

**Comment by brettz9** [comment]
I think bundlers are pretty ES-aware. I don't think they'd strip out things which were actually in use. I believe they can factor out dead code. But anyways, just something to think about.

**Comment by thelonious** [comment]
To clarify, if I have the following code:

```javascript
someInstance[methodName]()
```

You can know what methods are on `someInstance` since you can determine its type; however, if `methodName` some from outside your program, you have no way of knowing which method in your someInstance class is going to be invoked. The only safe thing to do is to keep all methods on that class.

**Comment by brettz9** [comment]
Ah, gotcha...

**Comment by brettz9** [comment]
But I'd probably advise against that for security reasons. I think modern JavaScript has fixed or is fixing this, but IIRC, one could do things with `__proto__`. I know lgtm.com warns against this kind of dynamic method use (a helpful site for catching more bugs than ESLint does).

https://lgtm.com/projects/g/thelonious/kld-intersections/alerts/?mode=list

(Btw, you can have the warnings in dist ignored by this site, by adding a file `lgtm.yml` in project root with this content:

```yml
extraction:
  javascript:
    index:
      filters:
        - exclude: "dist"
```

**Comment by thelonious** [comment]
It's hard to see how my dispatch code could be abused, but I've changed it over to a switch with explicit calls. That being said, there's still no way a bundler can know which method is being called because the value that invokes a given method comes from outside of the library.

I'll have to check out lgtm.

**Comment by thelonious** [comment]
@brettz9 I think SvgShapes is stable for now. I tested it against all SVG shape and path commands and it seems to be working. Just letting you know in case you wanted to give it a shot but were still hesitant. I may go ahead and push a new release.

**Comment by brettz9** [comment]
The API looks great. Eager to try it out as I have a chance.

**Pull request merged**
